# [Task]: T042
# Reminder Service Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-reminder-service
  labels:
    app: reminder-service
    app.kubernetes.io/name: reminder-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: reminder-service
