{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.database.name" . }}
  labels:
    {{- include "todo-chatbot.database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "todo-chatbot.database.selectorLabels" . | nindent 4 }}
  clusterIP: None
{{- end }}
