# [Task]: T049
# Recurring Service Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-recurring-service
  labels:
    app: recurring-service
    app.kubernetes.io/name: recurring-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8003
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: recurring-service
